---
apiVersion: v1
kind: Namespace
metadata:
  name: "sno1-jct"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-bmc-secret
  namespace: sno1-jct
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: bmc-secret
    creationPolicy: Orphan
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: "gmbros/sno1/bmc-secret"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-pull-secret
  namespace: sno1-jct
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: pull-secret
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: "gmbros/sno1/pull-secret"
