apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: "sno1-jct"
  namespace: "sno1-jct"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  holdInstallation: false
    # HoldInstallation will prevent installation from happening when true.
    # Inspection and validation will proceed as usual, but once the
    # RequirementsMet condition is true, installation will not begin until this field is set to false.
  baseDomain: "gmbros.local"
  pullSecretRef:
    name: "pull-secret"
  clusterImageSetNameRef: "openshift-mirror"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCE2WT3sHsRyLL0fgz5QaQF5y4QT7FSweru4bA/5P8vxDx1UR/phjxW0Rk+qWGkTnCA12845NAOB+v+uG8hcX+faKPnZRk/3YCFES9KYN/of0wzp0bdulsDodoAsYEuLGyxFkVQWyU/FIM5N2yG8iHNk93sNThGATFN6MB8F1perG81zUT9GGJja8Hmvqci8nQInYkT5uNAaKFhBqg3Um0UTJJu7RjUtWbbrIepPul/i/PhkyoRLc08IIonXHn07vY8CH/GRbrlM/CZ1ZGSc5NtjNYQPH6/VxMtq2Uga3OorlKKErm3UzVI968zETSJUI+PDrZAK+kfxJ2PvGKqN+ypVoXaIRkviWyU4WNNbsJmlqwTTu+bz9psdp6KBVLEqkm99DDGblgoJpHFFWxZyh7Z61cBzzCdNrYhkJ/9Testh4mAVHpkjpD6+ys8edw9qHCHiNQkPrjQysdSOKf/QQ6a9/yPkNf48Ptp9DjK5tVPZAlDHx7of9ixEi20Rmgaw7c="
  clusterName: "sno1-jct"
  networkType: "OVNKubernetes"
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: 10.12.0.0/24
  ## Not used in SNO deployments, but required by the API.  The SNO installer will automatically assign VIPs from the machineNetwork CIDR.
  # apiVIPs:
  #   - 10.12.0.217
  # ingressVIPs:
  #   - 10.12.0.218
  serviceNetwork:
    - cidr: 172.30.0.0/16
  extraLabels:
    ManagedCluster:
      ocp: "true"
      config-version: "v420-20260422"
  templateRefs: # https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.13/html-single/multicluster_engine_operator_with_red_hat_advanced_cluster_management/index#default-templates
    - name: ai-cluster-templates-v1
      namespace: open-cluster-management
  # extraManifestsRefs: # https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.13/html-single/multicluster_engine_operator_with_red_hat_advanced_cluster_management/index#mirror-images-disconnected
  #   - name: extra-manifests-cm

  ########################################################
  # Nodes in sno1-jct
  ########################################################
  nodes:
    - hostName: "sno1-jct"
      role: "master"
      bmcAddress: "redfish-virtualmedia+http://10.12.0.210:8000/redfish/v1/Systems/sno1-jct"
      bmcCredentialsName:
        name: "bmc-secret"
      bootMACAddress: "00:50:56:0c:00:db"
      bootMode: "UEFI"
      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management
      rootDeviceHints:
        deviceName: "/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0"
      nodeNetwork:
        interfaces:
          - name: "ens192"
            macAddress: "00:50:56:0c:00:db"
        config:
          interfaces:
            - name: ens192
              type: interface
              state: up
              ipv4:
                enabled: true
                dhcp: false
                address:
                  - ip: 10.12.0.219
                    prefix-length: 28
              mtu: 8950
          dns-resolver:
            config:
              server:
                - 10.12.0.1
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 10.12.0.1
                next-hop-interface: ens192
  ########################################################
