apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
  ### SNO1-JCT DEPLOYMENT ###
  - sno1-jct/resources.yaml
  #- sno1-jct/sno1-jct.yaml
