---
apiVersion: v1
data:
  ack-4.15-kube-1.29-api-removals-in-4.16": "true"
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Record administrator acknowledgments of update gates defined in the admin-gates ConfigMap in the openshift-config-managed namespace.
  name: admin-acks
  namespace: openshift-config
