---
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-image-4-20-19
  namespace: openshift-config-managed
  labels:
    release.openshift.io/verification-signatures: ""
binaryData:
## Steps to get the value:
# VERSION="4.22.14"
# DIGEST=$(oc adm release info quay.io/openshift-release-dev/ocp-release:${VERSION}-x86_64 -o jsonpath='{.digest}' | cut -d':' -f2)
# BASE64_VAL=$(curl -s "https://mirror.openshift.com/pub/openshift-v4/signatures/openshift/release/sha256=${DIGEST}/signature-1" | base64 -w 0)
# echo "Key name: sha256-${DIGEST}"
# echo "binaryData value:"
# echo "${BASE64_VAL}"
  sha256-e74e45ada5ab6325586e559ea69b7fd23bfe620af960bef33af19cadea8db7d2: owGbwMvMwMEoOU9/4l9n2UDG0wf6khiyFpv8rVZKLsosyUxOzFGyUqhWysxNTE8Fs1Lyk7NTi3RzE/My01KLS3RTMtOBFFBKqTgj0cjUzCrV3CTVxDQxJdE0McnM2MjU1MIs1dTUMjXRzDLJPC3FyDgpLdXMyCAxzdLMICk1zdg4Mc3QMjkxJTXRIiXJPMVIqVZHQamksgBknVJiSX5uZrJCcn5eSWJmXmqRQnFmel5iSWlRqhJQVWZKal5JZkklssOKUtNSi1LzksHaC0sTK/Uy8/XzC1LzijMy00qA0jmpicWpuimpZfr5yQUwvpWJnpGRnqGJboWFWbyZiVItyBH5BSWZ+XnQEEguSgU6pghkalBqioJHYomCP9DUYJCpCsFAV2XmpSs4lpZk5APDrVLBQM9AzxBoTCeTDAsDIwcDGysTKFgZuDgFYIF9Zh7/P10J3q8/miP22vNq/e6IeaKxYtLO3Ud032cuUGb9oWCt9XPHJS2l9ouLf8zu7Fjocl2Qd7bYabHddQdv+26SmVFx4KXEQZaS2x1i+0x1y3i9uOq/ZjtmmXguEGBd8vaAwbXpLz/mh25WWz2Vq/5V19dWXdHlBrotTVUbj1m3vP1c2CM3OajUIyXu3Kknf7ysHlVuztRLP/uT6+blOI79PcqHv878wJH+6+ld21OcG15rFzKzvF7i/iz18LVy9VVy8v73/XUPpDQb7d/z8b1Q413JVZ5z5tm9W2/14vJC57r3Hlbts1nO1hnlTZoe9WcFY6RfVYrG2qym+UbPMls3f61X1L5ufvf7k9n3ozfkT5z89JRtc4hv/qVqVkf5X3/EBTgfzU3kPbvX8PAns+Zfa3YcvPkpWY79Q4REhWXL/9Ma6fypKuZpT9uEshdOaTCMjq9QZmT+mND2eYNuVcajopnMd9Zvz1tSNvXZVSUfm7PZ27hE34Q80f9ZvCJ9O9Oxg5aTs/9MvV1p2CVn6hf+yHDqwrdXozen1Z668+ryrgoGw+6/fDocj0ttb966EPBirdrmJMW5V8t3f5yYH/1ycf/Z16E7X1UFms8wejPl0a3dvT8PNH1MdauIrRafKZBx6/BXhn39jxf8kv/OtznIaWvp+ncPNffUBxzQYG7b1Gtbk/BcTyz44Z+gllyGqSdLvFhmKncum7jv5ynuM/kA