---
apiVersion: v1
kind: ConfigMap
metadata:
  name: site-data-common
  namespace: ztp-policy
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
data:
  ########################################################
  # Global vars
  ########################################################
  mgmt-name: jct-ocp4
  mgmt-domain: gmbros.local
  install-plan-approval: Manual
