---
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
data:
  htpasswd: '{{hub fromSecret "ztp-policy" (printf "site-secret-%s" .ManagedClusterName) "htpasswd" hub}}'
