---
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
data:
  htpasswd: '{{hub fromSecret "ztp-policy" "site-secret" (printf "%s-htpasswd" .ManagedClusterName) hub}}'
