---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-upgrade
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: policies/hub-upgrade
    repoURL: 'https://github.com/jtovarro/core-ztp.git
    targetRevision: main
  project: policy-app-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 1
        maxDuration: 3m0s
      limit: 1000