---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/managedclustersetbinding.yaml
- resources/namespace.yaml
- resources/site-data.yaml
- resources/vss-site-secret.yaml
- v420-20260422
- openshift-upgrade

generators: []
