---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vss-site-secret
  namespace: ztp-policy
spec:
  type: kv-v2 
  mount: secret
  path: gmbros/sno1/site-secret
  destination:
    name: site-secret
    create: true
    labels:
      argocd.argoproj.io/secret-type: repository
  refreshAfter: 30s
  vaultAuthRef: vault-secrets-operator/vault-auth
